Repository juseonghyun/SSGtube, pull requests merged in 2024-05, with the labels that each got.

#2 Init/#1 init
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  app/src/main/java/com/example/ssg_tube/Constants.kt
  app/src/main/java/com/example/ssg_tube/MainActivity.kt
  app/src/main/java/com/example/ssg_tube/data/db/DBManager.kt
  app/src/main/java/com/example/ssg_tube/data/model/CategoryResponse.kt
  app/src/main/java/com/example/ssg_tube/data/model/ChannelResponse.kt
  app/src/main/java/com/example/ssg_tube/data/model/SearchResponse.kt
  app/src/main/java/com/example/ssg_tube/data/model/VideoResponse.kt
  app/src/main/java/com/example/ssg_tube/data/remote/YouTubeAPI.kt
  app/src/main/java/com/example/ssg_tube/network/RetroClient.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/DetailModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/MyPageModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/detail/DetailFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/home/HomeFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/search/SearchFragment.kt
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/menu/menu_navi.xml
  app/src/main/res/navigation/main_navi.xml
  app/src/main/res/values/colors.xml
Labels: init

#4 fix: navagation bottom 넓던것 수정
  app/src/main/java/com/example/ssg_tube/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: fix

#12 Enhancement/#11 search
  app/src/main/java/com/example/ssg_tube/Constants.kt
  app/src/main/java/com/example/ssg_tube/data/model/SearchResponse.kt
  app/src/main/java/com/example/ssg_tube/data/remote/YouTubeAPI.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/SearchItemModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/search/SearchAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/search/SearchFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/bg_search.xml
  app/src/main/res/drawable/ic_loading.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#14 Enhancement/#13 home
  app/build.gradle.kts
  app/src/main/java/com/example/ssg_tube/Constants.kt
  app/src/main/java/com/example/ssg_tube/MainActivity.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/CategoryVideoAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/ChannelAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/HomeFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/HomeViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/PopularVideoAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/VideoModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/mypage/MyPageFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/home/HomeFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/util/util.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/rv_category_video_item.xml
  app/src/main/res/layout/rv_channel_item.xml
  app/src/main/res/layout/rv_popular_video_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#15 Enhancement/#11 search
  app/src/main/java/com/example/ssg_tube/data/remote/YouTubeAPI.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/MyPageModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/SearchItemModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchViewModel.kt
  app/src/main/res/layout/search_item.xml
Labels: enhancement

#22 Feature/#18 mypage
  app/src/main/java/com/example/ssg_tube/Constants.kt
  app/src/main/java/com/example/ssg_tube/MainActivity.kt
  app/src/main/java/com/example/ssg_tube/data/db/DBManager.kt
  app/src/main/java/com/example/ssg_tube/data/model/ChannelResponse.kt
  app/src/main/java/com/example/ssg_tube/data/model/SearchResponse.kt
  app/src/main/java/com/example/ssg_tube/data/model/VideoResponse.kt
  app/src/main/java/com/example/ssg_tube/data/remote/YouTubeAPI.kt
  app/src/main/java/com/example/ssg_tube/presentaion/SharedViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/HomeFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/HomeViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/VideoModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/mypage/MyPageFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/mypage/MyPageViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/util/util.kt
  app/src/main/res/drawable/bg_mybackground.jpeg
  app/src/main/res/drawable/bg_myicon.png
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_back2.xml
  app/src/main/res/drawable/ic_blank_heart.xml
  app/src/main/res/drawable/ic_full_heart.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: feat

#27 Design/#25 design
  app/src/main/java/com/example/ssg_tube/Constants.kt
  app/src/main/java/com/example/ssg_tube/MainActivity.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailViewModel.kt
  app/src/main/res/drawable/bg_navigation_bar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/rv_category_video_item.xml
  app/src/main/res/layout/rv_popular_video_item.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/values/strings.xml
Labels: design, Refactor

#28 Enhancement/#23 home
  app/src/main/java/com/example/ssg_tube/Constants.kt
  app/src/main/java/com/example/ssg_tube/MainActivity.kt
  app/src/main/java/com/example/ssg_tube/data/model/SearchResponse.kt
  app/src/main/java/com/example/ssg_tube/data/repository/YoutubeRepositoryImpl.kt
  app/src/main/java/com/example/ssg_tube/presentaion/SharedViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/detail/DetailViewModel.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/HomeFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/home/PopularVideoAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/model/SearchToken.kt
  app/src/main/java/com/example/ssg_tube/presentaion/mypage/MyPageFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/repository/YoutubeRepository.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchViewModel.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/anim/slide_in.xml
  app/src/main/res/anim/slide_out.xml
  app/src/main/res/drawable/custom_ripple_effect.xml
  app/src/main/res/drawable/ic_floating_button.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/transition/fade.xml
  app/src/main/res/transition/slide_right.xml
Labels: feat, design

#30 style: 라인 정렬, enhancement: 스크롤뷰
  app/src/main/java/com/example/ssg_tube/Constants.kt
  app/src/main/java/com/example/ssg_tube/MainActivity.kt
  app/src/main/java/com/example/ssg_tube/presentaion/mypage/MyPageFragment.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchAdapter.kt
  app/src/main/java/com/example/ssg_tube/presentaion/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: enhancement
